#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::Cell qw (expandcell);

die "Usage: $0 cellname \n" if $#ARGV != 0;
my $c = shift;

my $cell = expandcell($c);
print "AFS::CODE = $AFS::CODE\n";
print "cell = $cell\n";
