#!/usr/local/bin/perl -w

use blib;
use AFS::Cell qw (expandcell);

die "Usage: $0 cellname \n" if $#ARGV != 0;
my $c = shift;

my $cell = expandcell($c);
print "AFS::CODE = $AFS::CODE\n";
if (defined $cell) {
    print "cell = $cell\n";
}
