#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::Cell qw (whichcell);

die "Usage: $0 dir \n" if $#ARGV != 0;
my $dir = shift;

$cell = whichcell($dir);
print "AFS::CODE = $AFS::CODE\n";
print "which cell = $cell\n";
