#!/usr/local/bin/perl

require 'ctime.pl';

use AFS;

AFS::raise_exception(1);

$server =ktc_principal("afs","",localcell);

($token,$client) = ktc_GetToken($server);

&ktc_ForgetAllTokens;

system "./tokens";

ktc_SetToken($server,$token,$client,0);

system "./tokens";

