#!/usr/local/bin/perl
require 'ctime.pl';
use AFS;
print "\nTokens held by the Cache Manager:\n\n";
$context =0;
 while( $server = ktc_ListTokens($context)) {
   if ( ($token,$client) = ktc_GetToken($server)) {
       $user = $client->name;
       $user .= "." . $client->instance if ($client->instance);
       if ($user eq '' || $user =~ /Unix UID/) { printf("Tokens"); }
       elsif ($user =~ /AFS ID/) { printf("User's (%s) tokens",$user); }
       print " for ", $server->principal," ";
       if ($token -> endTime <= time) { print "[>> Expired <<]\n"; }
       else {
           chop($expire = substr(&ctime($token->endTime),4,13));
           print "[Expires $expire]\n";
       }
#        chop($started = substr(&ctime($token->startTime),4,13));
#        print "[Created $started]\n";
   }
 }
print"   --End of list--\n";
