#!/usr/local/bin/perl -w

use blib;
use AFS::KTC_EKEY;

die "Usage: $0 prompt verify cell\n" if ($#ARGV != 2);

my $prompt = shift;
my $verify = shift;
my $cell = shift;

my $key = AFS::KTC_EKEY->ReadPassword($prompt, $verify, $cell);
print "KEY = ", $key->string, " \n";

