#!/usr/local/bin/perl -w

use blib;
use AFS::KTC_EKEY;

die "Usage: $0 str cell\n" if ($#ARGV != 1);

my $string = shift;
my $cell = shift;

$key = AFS::KTC_EKEY->StringToKey($string, $cell);
print "KEY = ", $key->string, " \n";
