#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::KTC_EKEY;

die "Usage: $0 prompt\n" if ($#ARGV != 0);

my $prompt = shift;

my $reason = '';
my $string = AFS::KTC_EKEY->UserReadPassword($prompt, $reason);
if ($reason) { print "reason = $reason\n"; }
if ($string) { print "password = ($string)\n"; }
