---
abstract: 'Perl interface to AFS programming APIs'
author:
  - 'Norbert E Gruener <nog@MPA-Garching.MPG.de>'
build_requires:
  Test::More: 0
configure_requires: {}
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AFS
no_index:
  directory:
    - examples
    - inc
    - src/inc
requires:
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 2.6.3
