name: AFS
version: 2.2.2
abstract: Perl interface to AFS programming APIs
author: Norbert E Gruener <nog@MPA-Garching.MPG.de>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.005
no_index:
  directory:
    - src/inc
    - inc
generated_by: Module::Install version 0.31
