#!/usr/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

my ($vldb, $server, $part, $volume, $ok);

die "Usage: $0 server partition volume \n" if $#ARGV != 2;

$server = shift;
$part   = shift;
$volume = shift;

$vldb = AFS::VLDB->new;
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

$ok = $vldb->addsite($server, $part, $volume);
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

print "Added replication site $server /vicep$part for volume $volume \n";
