#!/usr/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

my ($vldb, $volume, $server, $part, $ok);

die "Usage: $0 volume dest_server dest_partition \n" if $#ARGV != 2;

$volume = shift;
$server = shift;
$part   = shift;

$vldb = AFS::VLDB->new;
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

$ok = $vldb->changeloc($volume, $server, $part);
print "Error: ", $AFS::CODE, ",\n" if ($AFS::CODE);

print "Changed location to $server /vicep$part for volume $volume \n";
