#!/usr/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

our ($verbose, $vldb);

die "Usage: $0 [verbose]\n" if $#ARGV > 0;

$verbose = shift || 0;

$vldb = AFS::VLDB->new($verbose);
if ($AFS::CODE) { print "Error Code: $AFS::CODE\n"; }
else { print "OK \n"; }

test_it($vldb);

sub test_it {
    my $self = shift;
    $self->DESTROY;
}
