#!/usr/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

our ($vldb, $volume, $ok);

die "Usage: $0 volume\n" if $#ARGV != 0;

$volume = shift;

$vldb = AFS::VLDB->new;
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

$ok = $vldb->lock($volume);
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);
