#!/usr/local/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

my ($vldb, $volume, $ok);

die "Usage: $0 volume\n" if $#ARGV != 0;

$volume = shift;

$vldb = AFS::VLDB->new;
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

$ok = $vldb->lock($volume);
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

print "Locked VLDB entry for volume $volume \n" if $ok;
