#!/usr/local/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

my ($vldb, $volume, $ok);

die "Usage: $0 volume \n" if $#ARGV != 0;

$volume = shift;

$vldb = AFS::VLDB->new;

$ok = $vldb->syncvldbentry($volume);
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);
