#!/usr/local/bin/perl -w

use blib;

use strict;
use AFS::VLDB;

my ($vldb, $server, $partition, $ok);

die "Usage: $0 server [partition]\n" if $#ARGV < 0;

$server    = shift;
$partition = shift;

$vldb = AFS::VLDB->new;
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

if (defined $partition) {
    $ok = $vldb->syncserv($server, $partition);
    print "Error: $AFS::CODE \n" if ($AFS::CODE);
    print "Server $server partition $partition synchronized with VLDB \n" if $ok;
}
else {
    $ok = $vldb->syncserv($server);
    print "Error: $AFS::CODE \n" if ($AFS::CODE);
    print "Server $server synchronized with VLDB \n" if $ok;
}
