#!/usr/local/bin/perl -w

use strict;
use blib;

use AFS::ACL;

die "Usage: $0 rights \n" if $#ARGV != 0;

my $rights = shift;
print "Flag($rights) = ", AFS::ACL->ascii2rights($rights), "\n";
print "AFS::CODE = $AFS::CODE (", ($AFS::CODE+0), ")\n";
