#!/usr/local/bin/perl -w

use strict;
use blib '../blib/';

use AFS::ACL;

die "Usage: $0 rights\n" if $#ARGV != 0;

my $rights = shift;
print "Rights($rights) = ", AFS::ACL->crights($rights), "\n";
print "AFS::CODE = $AFS::CODE (", ($AFS::CODE+0), ")\n";
