#!/usr/local/bin/perl -w

use strict;
use blib '../blib/';

use AFS::ACL;

die "Usage: $0 flag \n" if $#ARGV != 0;

my $flag = shift;
print "Rights($flag) = ", AFS::ACL->rights2ascii($flag), "\n";
print "AFS::CODE = $AFS::CODE (", ($AFS::CODE+0), ")\n";
