=head1 NAME

afsperlobj - Objects used by the AFS module

=head1 SYNOPIS

  use AFS;

  AFS::ACL
  AFS::KA_AUTHSERVER
  AFS::KTC_TOKEN
  AFS::KTC_PRINCIPAL
  AFS::KTC_ENCRYPTIONKEY
  AFS::PTS_SERVER

=head1 DESCRIPTION

This document describes the objects used by the AFS module.

=head1 AFS::ACL

=head1 AFS::KA_AUTHSERVER

=head1 AFS::KTC_TOKEN

=head1 AFS::KTC_PRINCIPAL

   AFS::KTC_PRINCIPAL::new("$user.$instance@$cell");
   AFS::KTC_PRINCIPAL::new($user,$instance,$cell);
   $princ = newprincipal(...); # same as above
   $princ = ktc_principal(...); # same as above

=head1 AFS::KTC_ENCRYPTIONKEY

   $DESKEY = ka_StringToKey($str, $cell=0);
   $DESKEY = ka_des_string_to_key($str);
   $DESKEY = ka_ReadPassword($prompt, $verify=0, $cell=0);

=head1 AFS::PTS_SERVER


=head1 SEE ALSO

  afsperlacl
  afsperlka 
  afsperlktc
  afsperlpts
