#!/usr/local/bin/perl -w

use blib '../blib/';

use AFS::Utils qw (get_server_version);

die "Usage: $0 service host\n" if ($#ARGV !=1);

my $service = shift;
my $host = shift;

my $version = get_server_version($service, $host);
print "AFS::CODE = $AFS::CODE\n";
print "Host $host AFS Service $service: Version = $version\n";
