#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::FS qw(getquota);

die "Usage: $0 path\n" if $#ARGV==-1;

my $path = shift;

my $quota = getquota($path);
print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
print "quota = $quota\n";

