#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(getquota);

my ($path, $quota);

die "Usage: $0 path\n" if ($#ARGV == -1);

$path = shift;

$quota = getquota($path);
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);
print "quota = $quota\n";

