#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(isafs);

my ($path, $ok);

die "Usage: $0 path\n" if ($#ARGV == -1);

$path = shift;

$ok = isafs($path);
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);
print "ok isafs = $ok\n";
