#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(lsmount);

my ($path, $vol);

die "Usage: $0 path\n" if ($#ARGV != 0);

$path = shift;

$vol = lsmount($path);
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);
print "Vol = $vol \n";

