#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(rmmount);

my ($mountp, $ok);

die "Usage: $0 mountp\n" if ($#ARGV == -1);

$mountp = shift;

$ok = rmmount($mountp);
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);
print "ok rmmount = $ok\n";
