#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(rmmount);

die "Usage: $0 mountp\n" if ($#ARGV==-1);

my $mountp = shift;

my $ok = rmmount($mountp);
print "AFS::CODE = $AFS::CODE\n";
print "ok rmmount = $ok\n";
