#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::FS qw(setquota);

die "Usage: $0 path quota\n" if $#ARGV==-1;

my $path = shift;
my $quota = shift;

my $ok = setquota($path, $quota);
print "AFS::CODE = $AFS::CODE\n";
print "ok setquota = $ok\n";

