#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(setquota);

my ($path, $quota, $ok);

die "Usage: $0 path quota\n" if ($#ARGV == -1);

$path  = shift;
$quota = shift;

$ok = setquota($path, $quota);
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);
print "ok setquota = $ok\n";

