#!/usr/local/bin/perl -w

use blib;
use AFS::FS qw(whereis);

my ($dir, $ip, @hosts);

die "Usage: $0 dir ip\n" if ($#ARGV == -1);

$dir = shift;
$ip  = shift;

@hosts = whereis($dir, $ip);
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

foreach my $host (@hosts) {
    print " $host\n";
}
