#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 user group\n" if $#ARGV != 1;

$user = shift;
$group = shift;

$pts = newpts;

$success = $pts ->adduser($user,$group);

print "success  = $success\n";

