#!/usr/local/bin/perl

use AFS;

print "name: "; chop($name=<STDIN>);
print "new id: ";chop($new=<STDIN>);

  $pts = AFS::PTS::new;

  print "AFS::PTS::new AFS::CODE = $AFS::CODE\n";

   $success = $pts ->chid($name,$new);

  print "chid AFS::CODE = $AFS::CODE\n";

  print "success  = $success\n";

 $pts = '';


