#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 pos\n" if $#ARGV !=0;

$pos = shift;

$pts = newpts;

   $entry = $pts ->dumpentry($pos);

    foreach $key ( sort keys %$entry) {
        printf("%20s =>  %s\n", $key, $$entry{$key});
    }

 $pts = '';


