#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

  $annon= shift;

  $pts = newpts;

print "----- scaler\n";

  $name = "nog";

  $id = $pts ->id($name,$annon);

  print "id = $id\n";


print "----- array\n";

  @names = ('nog','testafs','hans','foobar');

  @ids = $pts ->id(\@names,$annon);

  foreach $id (@ids) {
     print "id = $id\n";
  }
  
print "----- hash\n";

  @ids = ('nog','testafs','hans','foobar');
  foreach $id (@ids) { $idhash{$id} = ''; }

  $hash = $pts ->id(\%idhash,$annon);
  foreach $key (keys %$hash) {
     print "$key = $$hash{$key}\n";
  }
  

