#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 name convertids convertflags\n" if $#ARGV != 2;

$name = shift;

$convert = shift;

$flags = shift;

$pts = newpts;

$entry = $pts ->listentry($name,$convert,$flags);

  foreach $key ( sort keys %$entry) {
        printf("%20s =>  %s\n", $key, $$entry{$key});
  }

