#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

  $annon= shift;

  $pts = newpts;

print "----- scaler\n";

  $id = "4337";

  $name = $pts ->name($id,$annon);

  print "name = $name\n";


print "----- array\n";

  @ids = (4337, 231, 105,  32766,32000);

  @names = $pts ->name(\@ids,$annon);

  foreach $name (@names) {
     print "name = $name\n";
  }
  
print "----- hash\n";

  @ids = (4337, 231, 105, 32000, 32766);
  foreach $id (@ids) { $idhash{$id} = ''; }

  $hash = $pts ->name(\%idhash,$annon);

  foreach $key (keys %$hash) {
     print "$key = $$hash{$key}\n";
  }
  

