#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 name convertids\n" if $#ARGV !=1;

$name = shift;
$convert = shift;

$pts = newpts;

@members = $pts ->owned($name,$convert,$over);

  print "over = $over\n";

  print "groups owned by $name\n";
    foreach $mem (sort @members) {
        printf("  $mem\n");
    }

