#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 id name oid newid\n" if ($#ARGV != 3);

$id = shift;

$name= shift;

$oid = shift;

$newid = shift;

$pts = newpts;

$ok = $pts ->PR_ChangeEntry($id, $name, $oid, $newid);

print "ok = $ok\n";

