#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 name id ownerid\n" if ($#ARGV != 2);

$name= shift;

$id = shift;

$ownerid = shift;

$pts = newpts;

$theid = $pts ->PR_INewEntry($name, $id, $ownerid);

print "id = $theid\n";

