#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 id\n" if $#ARGV != 0;

$id = shift;

$pts = newpts;

$entry = $pts ->PR_ListEntry($id);

  foreach $key ( sort keys %$entry) {
        printf("%20s =>  %s\n", $key, $$entry{$key});
  }


