#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

  @names = ('schemers','torg','dennis','foobar');

  @ids = newpts ->PR_NameToID(\@names);

  foreach $id (@ids) {
     print "id = $id\n";
  }
  
