#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 name isgroup ownerid\n" if ($#ARGV != 2);

$name= shift;

$isgroup = shift;

$ownerid = shift;

$pts = newpts;

if ($isgroup) { $flag = &AFS::PRGRP; } 
else { $flag = &AFS::PRUSER; }

$id = $pts ->PR_NewEntry($name, $flag, $ownerid);

print "id = $id\n";

