#!/usr/local/bin/perl

use AFS;

print "old name: "; chop($old=<STDIN>);
print "new name: ";chop($new=<STDIN>);
$name = shift;

  $pts = AFS::PTS::new;

  print "AFS::PTS::new AFS::CODE = $AFS::CODE\n";

   $success = $pts ->rename($old,$new);

  print "rename AFS::CODE = $AFS::CODE\n";

  print "success  = $success\n";

 $pts = '';


