#!/usr/local/bin/perl

use AFS;

print "name: "; chop($name=<STDIN>);
print "access: "; chop($access=<STDIN>);

  $pts = AFS::PTS::new;

  print "AFS::PTS::new AFS::CODE = $AFS::CODE\n";

   $success = $pts ->setaccess($name,$access);

  print "setaccess AFS::CODE = $AFS::CODE\n";

  print "success  = $success\n";

 $pts = '';


