#!/usr/local/bin/perl

use AFS;

print "name: "; chop($name=<STDIN>);
print "maxgroups: "; chop($ngroup=<STDIN>);

  $pts = AFS::PTS::new;

  print "AFS::PTS::new AFS::CODE = $AFS::CODE\n";

   $success = $pts ->setgroupquota($name,$ngroup);

  print "setgroupquota AFS::CODE = $AFS::CODE\n";

  print "success  = $success\n";

 $pts = '';


