#!/usr/local/bin/perl

use AFS;

print "id : "; chop($id=<STDIN>);
print "isgroup: "; chop($isgroup=<STDIN>);

  $pts = AFS::PTS::new;

  print "AFS::PTS::new AFS::CODE = $AFS::CODE\n";

   $success = $pts ->setmax($id,$isgroup);

  print "setmax AFS::CODE = $AFS::CODE\n";

  print "success  = $success\n";

 $pts = '';


