#!/usr/local/bin/perl

use AFS;

die "Usage: $0 fast cell ip\n" if ($#ARGV !=2);

$fast= shift;

$cell = expandcell(shift);
$ip = shift;

@down = checkservers($fast,$cell,$ip);

foreach $server (@down) {
  print " $server\n";

}
