#!/usr/local/bin/perl

use AFS cleanacl;

die "Usage: $0 path\n" if ($#ARGV==-1);

$path = shift;

$ok =  cleanacl($path);

 print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
 print "ok = $ok\n";

