#!/usr/local/bin/perl

use AFS copyacl;

die "Usage: $0 from to\n" if ($#ARGV==-1);

$from = shift;
$to = shift;

 $ok =  copyacl($from, $to);

 print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
 print "ok = $ok\n";

