#!/usr/local/bin/perl

use AFS crights;

die "Usage: $0 rights\n" if $#ARGV != 0;

$rights=shift;

$value = crights($rights);

  print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
  print "value = $value\n";

