#!/usr/local/bin/perl

use AFS getcellstatus;

$cell = shift;

#$setuid = AFS::getcellstatus;
$setuid = getcellstatus($cell);

print "AFS::CODE = $AFS::CODE\n";

print "setuid allowed  = $setuid\n";

