#!/usr/local/bin/perl

use AFS;

$file = shift;

($Cell, $Volume, $Vnode, $Unique ) = AFS::getfid($file);

print "AFS::CODE = $AFS::CODE\n";
print "(Cell, Volume, Vnode, Unique ) = ($Cell, $Volume, $Vnode, $Unique )\n";
AFS::getfid($file);
