#!/usr/local/bin/perl

use AFS getquota;

die "Usage: $0 path\n" if $#ARGV==-1;

$path = shift;

$quota = getquota($path);

print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";

print "quota = $quota\n";
