#!/usr/local/bin/perl

use AFS lsmount;

die "Usage: $0 path\n" if ($#ARGV != 0);

$path = shift;

$mount  = lsmount($path);

print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
print "mount = $mount\n";

