#!/usr/local/bin/perl

use AFS setacl,getacl,modifyacl,newacl;

$dir = shift;

 $ok =  modifyacl($dir,newacl({"rjs" => "all"}));

 print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
 print "ok = $ok\n";

system "fs la $dir";

 $ok =  modifyacl($dir,newacl({"rjs" => "none"}));

 print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
 print "ok = $ok\n";

system "fs la $dir";