#!/usr/local/bin/perl

use AFS rights2ascii;

die "Usage: $0 rights\n" if $#ARGV != 0;

$rights=shift;

$value = rights2ascii($rights);

  print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
  print "value = $value\n";

