#!/usr/local/bin/perl

use AFS setacl,getacl,crights;

$dir = shift;

$acl = AFS::ACL::new({"schemers"=>crights("all"),
        "rjs"=>crights("read")},{"opusl"=>crights("write")});

$ok = setacl($dir,$acl);

  print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";
  print "ok = $ok\n";

