#!/usr/local/bin/perl

use AFS setquota;

die "Usage: $0 path quota\n" if $#ARGV==-1;

$path = shift;
$quota = shift;

$ok = setquota($path,$quota);

print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";

print "ok = $ok\n";
