#!/usr/local/bin/perl -w

use blib '../blib/';

use AFS::CM qw (flushcb);

die "Usage: $0 path\n" if ($#ARGV==-1);

my $path = shift;

my $ok = flushcb($path);
print "AFS::CODE = $AFS::CODE (", ($AFS::CODE+0), ")\n";
print "ok = $ok\n";
