#!/usr/local/bin/perl -w

use blib;

use AFS::CM qw (flushvolume);

die "Usage: $0 path\n" if ($#ARGV==-1);

my $path = shift;

my $ok = flushvolume($path);
print "AFS::CODE = $AFS::CODE (", ($AFS::CODE+0), ")\n";
print "ok = $ok\n";
