#!/usr/local/bin/perl -w

use blib;

use AFS::CM qw (getcellstatus);

die "Usage: $0 cell\n" if ($#ARGV==-1);

my $cell = shift;

my $setuid = getcellstatus($cell);
print "AFS::CODE = $AFS::CODE\n";
printf("Setuid allowed: %s \n", $setuid ? 'yes' : 'no');
