#!/usr/local/bin/perl

use blib;

use strict;
use AFS::CM qw(getvolstats);

my ($path, $stats);

die "Usage: $0 path\n" if $#ARGV != 0;

$path = shift;

$stats = getvolstats($path);
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

foreach my $key (sort keys %$stats) {
    printf("%20s  %s\n", $key, $$stats{$key});

}
