#!/usr/local/bin/perl -w

use blib;

use AFS::CM qw (setcellstatus);

die "Usage: $0 cell setuid\n" if ($#ARGV==-1);

my $cell = shift;
my $setuid = shift;

my $ok = setcellstatus($setuid, $cell);
print "AFS::CODE = $AFS::CODE\n";
if (defined $ok) {
    printf("Command successfull: %s \n", $ok ? 'yes' : 'no');
}
