#!/usr/local/bin/perl

require 'ctime.pl';

use AFS;

AFS::raise_exception(1);

die "Usage: user\n" if ($#ARGV != 0);

$user  = ktc_principal(shift);
$key   = ka_ReadPassword($user->name."'s Password:");

$kas   = ka_AuthServerConn(ka_nulltoken, &AFS::KA_AUTHENTICATION_SERVICE);

$token = $kas->ka_Authenticate($user->name, $user->instance,
                               &AFS::KA_TICKET_GRANTING_SERVICE,
                               $key,time,time+600);

print "   startTime = ", &ctime($token -> startTime);
print "     endTime = ", &ctime($token -> endTime);



