#!/usr/local/bin/perl

require 'ctime.pl';

use AFS;

AFS::raise_exception(1);

die "Usage: admin\n" if ($#ARGV != 0);

$princ = ktc_principal(shift);
$key   = ka_ReadPassword($princ->name."'s Password:");
$token = ka_GetAdminToken($princ, $key, 300);

$kas   = ka_AuthServerConn($token, &AFS::KA_MAINTENANCE_SERVICE);

$kas   = '';
