#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: user \n" if ($#ARGV != 0);

  $user = ktc_principal(shift);
  $user->cell(localcell) if ($user->cell eq '');
$oldkey = ka_ReadPassword("Old Password:");
$newkey = ka_ReadPassword("New Password:",1,$user->cell);
 $token = ka_GetAdminToken($user, $oldkey, 300);
   $kas = ka_AuthServerConn($token, &AFS::KA_MAINTENANCE_SERVICE);
$ok = $kas->ka_ChangePassword($user->name, $user->instance, $oldkey, $newkey);

print "ok = $ok\n";

