#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: admin usertodelete\n" if ($#ARGV != 1);

$admin = ktc_principal(shift);
$deleteme = ktc_principal(shift);

$key = ka_ReadPassword("Admin Password:");

$token = ka_GetAdminToken($admin, $key, 300);

$kas = ka_AuthServerConn($token, &AFS::KA_MAINTENANCE_SERVICE);

$ok = $kas -> delete($deleteme->name, $deleteme->instance);

print "ok = $ok\n";



