#!/usr/local/bin/perl

use AFS;

die "Usage: $0 str\n" if ($#ARGV != 0);

$str = shift;

 $key = ka_des_string_to_key($str);

$string = $key -> string;

for ($i=0; $i<8; $i++) {
  printf("%o\n",ord(substr($string,$i,1)));
}
