#!/usr/local/bin/perl

use AFS;
AFS::raise_exception(1);

die "Usage: admin \n" if ($#ARGV != 0);

$princ = ktc_principal(shift);

$key = ka_ReadPassword("Admin Password:");

$token = ka_GetAdminToken($princ, $key, 300);

$kas = ka_AuthServerConn($token, &AFS::KA_MAINTENANCE_SERVICE);

$entry = $kas -> debug;

foreach $key (sort keys %$entry) {
  printf("%20s  %s\n",$key, $$entry{$key});

}
