#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: admin \n" if ($#ARGV != 0);

$princ = ktc_principal(shift);

$key = ka_ReadPassword("Admin Password:");

$token = ka_GetAdminToken($princ, $key, 300);

$kas = ka_AuthServerConn($token, &AFS::KA_MAINTENANCE_SERVICE);

($num_admins, $stats, $dstats) = $kas -> getstats;

print "num_admins = $num_admins\n";

print"stats-----\n";
foreach $key (sort keys %$stats) {
  printf("%20s  %s\n",$key, $$stats{$key});

}

print"dynamic stats-----\n";
foreach $key (sort keys %$dstats) {
  printf("%20s  %s\n",$key, $$dstats{$key});

}
