#!/usr/local/bin/perl

require 'ctime.pl';

use AFS;

die "Usage: $0 user\n" if ($#ARGV !=0);

$user = shift;

AFS::raise_exception(1);

$key = ka_ReadPassword("Password:");

$princ = ktc_principal($user);

$ok = ka_GetAuthToken($princ, $key, 300, $pw);

print "ok = $ok  pw = $pw\n";

