#!/usr/local/bin/perl

use AFS;
AFS::raise_exception(1);

die "Usage: admin user\n" if ($#ARGV != 1);

$princ = newprincipal(shift);
$user  = newprincipal(shift);

$key   = ka_ReadPassword($princ->name."'s Password:");
$token = ka_GetAdminToken($princ, $key, 300);

$kas   = ka_AuthServerConn($token, &AFS::KA_MAINTENANCE_SERVICE);

#$entry = $kas -> KAM_GetEntry($user->name, $user->instance);
$entry = $kas->getentry($user->name, $user->instance);

foreach $key (sort keys %$entry) {
  printf("%20s  %s\n",$key, $$entry{$key});
}
