#!/usr/local/bin/perl


use AFS ;

die "Usage: $0 name\n" if ($#ARGV != 0);

AFS::raise_exception(1);

$login = shift;

($name, $inst, $cell) = ka_ParseLoginName($login);

print "AFS::CODE = $AFS::CODE (",$AFS::CODE+0,")\n";

print "($name,$inst,$cell)\n";

