#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 prompt verify cell\n" if ($#ARGV != 2);

$prompt = shift;
$verify = shift;
$cell = shift;

$key = ka_ReadPassword($prompt, $verify, $cell);

$string = $key->string;

print "key\n";

for ($i=0; $i<8; $i++) {
  printf("%o\n",ord(substr($string,$i,1)));
}
