#!/usr/local/bin/perl

require 'ctime.pl';

use AFS;
AFS::raise_exception(1);

die "Usage: host admin user\n" if ($#ARGV != 2);

$host = shift;
$princ = ktc_principal(shift);
$user = ktc_principal(shift);

$key = ka_ReadPassword("Admin Password:");

$token = ka_GetAdminToken($princ, $key, 300);

$kas = ka_SingleServerConn($host,$token, &AFS::KA_MAINTENANCE_SERVICE);

$entry = $kas -> getentry($user->name, $user->instance);

foreach $key (sort keys %$entry) {
  printf("%20s  %s\n",$key, $$entry{$key});

}
