#!/usr/local/bin/perl

use AFS;

AFS::raise_exception(1);

die "Usage: $0 str cell\n" if ($#ARGV != 1);

$str = shift;
$cell = shift;

$key = ka_StringToKey($str,$cell);

print "key\n";

$string = $key->string;

for ($i=0; $i<8; $i++) {
  printf("%o\n",ord(substr($string,$i,1)));
}
