#!/usr/local/bin/perl

use AFS;

#AFS::raise_exception(1);

die "Usage: $0 prompt\n" if ($#ARGV != 0);

$prompt = shift;

$password = ka_UserReadPassword($prompt,$reason);

print "AFS::CODE = $AFS::CODE\n";
print "reason = $reason\n";

if ($password) {
  print "password = ($password)\n";
}
