#!/usr/local/bin/perl -w

use blib;

use strict;
use AFS::BOS;

my ($server, $cellname, $bos);

die "Usage: $0 server [cell]\n" if $#ARGV < 0;

$server   = shift;
$cellname = shift;

if ($cellname) { $bos = AFS::BOS->new($server, 0, 0, $cellname); }
else           { $bos = AFS::BOS->new($server); }
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

my @users = $bos->listusers;
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

if (defined $users[0]) {
    print "SUsers are: ", join(' ', @users), "\n";
}

$bos->DESTROY;
