#!/usr/bin/perl -w

use blib;

use strict;
use AFS::BOS;

my ($server, $cellname, $bos);

die "Usage: $0 server [cell]\n" if $#ARGV < 0;

$server   = shift;
$cellname = shift;

if ($cellname) { $bos = AFS::BOS->new($server, 0, 0, $cellname); }
else           { $bos = AFS::BOS->new($server); }
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

die "not yet tested ... \n";

print "bos->removekey()...\n";

my $ok = $bos->removekey(15); # single key
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

$ok = $bos->removekey([12, 15]); # multiple keys as array-ref
print "Error Code: $AFS::CODE\n" if ($AFS::CODE);

$bos->DESTROY;
