#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::PTS;

print "name: "; chop(my $name=<STDIN>);
print "new id: ";chop(my $new=<STDIN>);

my $pts = AFS::PTS->new;

my $ok = $pts->chid($name,$new);
print "chid AFS::CODE = $AFS::CODE\n";
print "success  = $ok\n";
