#!/usr/local/bin/perl -w

use blib;
use AFS::PTS;

die "Usage: $0 user group\n" if $#ARGV != 1;

my $pts = AFS::PTS->new;

my $user = shift;
my $group = shift;

my $ok = $pts->ismember($user, $group);
print "AFS::CODE = $AFS::CODE (", $AFS::CODE+0,")\n";
print "OK = $ok\n";
