#!/usr/local/bin/perl -w

use blib;
use AFS::PTS;

die "Usage: $0 name convertids convertflags\n" if $#ARGV != 2;

my $name = shift;
my $convert = shift;
my $flags = shift;

my $pts = AFS::PTS->new;

my $entry = $pts->listentry($name, $convert, $flags);

print "LIST:  AFS::CODE = $AFS::CODE\n";
foreach my $key ( sort keys %$entry) {
    printf("%20s =>  %s\n", $key, $$entry{$key});
}
