#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::PTS;

die "Usage: $0 name convertids\n" if ($#ARGV != 1);

my $name = shift;
my $convert = shift;

my $pts = AFS::PTS->new;

my $over = 1;
my @names = $pts->owned($name, $convert, $over);
print "AFS::CODE = $AFS::CODE\n";
print "OVER = $over \n";
print "Groups owned by $name\n";
foreach my $mem (sort @names) {
    print "  $mem\n";
}
