#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::PTS;

die "Usage: $0 id\n" if $#ARGV !=0;

my $id = shift;

my $pts = AFS::PTS->new;

$ok = $pts->PR_Delete($id);
print "AFS::CODE = $AFS::CODE\n";
print "success  = $ok\n";
