#!/usr/local/bin/perl -w

use blib;
use AFS::PTS;

die "Usage: $0 id\n" if ($#ARGV != 0);

my $id = shift;

my $pts = AFS::PTS->new;

my $over = 1;
my @names = $pts->PR_GetCPS($id, $over);
print "OVER = $over \n";
print "cps for $id\n";
foreach my $mem (sort @names) {
    print "  $mem\n";
}
