#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::PTS;

die "Usage: $0 uid gid\n" if $#ARGV != 1;

my $pts = AFS::PTS->new;

my $uid = shift;
my $gid = shift;

my $ok = $pts->PR_IsAMemberOf($uid, $gid);
print "AFS::CODE = $AFS::CODE (", $AFS::CODE+0,")\n";
print "OK = $ok\n";
