#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::PTS;

die "Usage: $0 id\n" if $#ARGV !=0;

my $id = shift;

my $pts = AFS::PTS->new;
my $over = 0;

my @members = $pts->PR_ListElements($id,$over);
print "over = $over\n";
print "members for $id\n";

foreach my $mem (sort @members) {
    printf("  $mem\n");
}
