#!/usr/local/bin/perl -w

use blib '../blib/';
use AFS::PTS;

print "old name: "; chop(my $old=<STDIN>);
print "new name: "; chop(my $new=<STDIN>);

my $pts = AFS::PTS->new;

$ok = $pts->rename($old, $new);
print "rename AFS::CODE = $AFS::CODE\n";
print "success  = $ok\n";
