#!/usr/bin/perl -w

use blib;

use strict;
use AFS::VOS;

my ($vos, $volume, $ok);

die "Usage: $0 volume\n" if $#ARGV < 0;

$volume = shift;

$vos = AFS::VOS->new;
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

$ok = $vos->backup($volume);
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

print "Created backup volume for $volume \n" if $ok;
