#!/usr/local/bin/perl -w

use blib;

use strict;
use AFS::VOS;

my ($vos, $server);

die "Usage: $0 server \n" if $#ARGV != 0;

$server = shift;

$vos = AFS::VOS->new;
print "Error: ", $AFS::CODE, "\n" if ($AFS::CODE);

my $stat = $vos->status($server);
print "AFS::CODE: $AFS::CODE \n";

if (defined $stat) { print "$stat"; }
