#!/usr/local/bin/perl

use AFS getcell;

$AFS::CODE = 0;

$ip = shift;

for ($i=0; $i < 1000 && $AFS::CODE==0; $i++) {

  ( $cell, @hosts) = getcell($i,$ip);
  
   print "AFS::CODE = $AFS::CODE\n";
   last if $AFS::CODE != 0;
  printf "cell $cell\n";
  foreach $host (@hosts) {
    printf(" $host\n");
  }
}
